###########################################################################
# If a new PR is opened and it lacks news file, then give them a gentle reminder.
###########################################################################

name: Comment on missing news file

on:
  pull_request:
    branches:
      - master

jobs:
  comment-on-missing-news-file:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout syslog-ng source
        uses: actions/checkout@v2

      - name: Check if a news file (or more) has been created
        run: |
          . .github/workflows/gh-tools.sh

          echo $(pwd)
          git fetch origin master ${{ github.event.pull_request.base.sha }}
          git diff ${{ github.event.pull_request.base.sha }} ${{ github.sha }}
          NEWS_FILES=$(git diff --name-only github.event.pull_request.base.sha ${{ github.sha }} | grep -E "news\/.*\.md")

          gh_export NEWS_FILES

      - name: Comment
        if: env.NEWS_FILES != ''
        run: |
          COMMENT_ENDPOINT=repos/${{ github.repository_owner }}/syslog-ng/issues/${{ github.event.number }}/comments
          COMMENT="No news file has been detected. Please write it, if applicable."

          hub api \
            ${COMMENT_ENDPOINT} \
            --field body="${COMMENT}"

